import { C_logo, C_logo2, C_logo3 } from "../components/imagepath";

export const data_company = [
  {
    id: 1,
    company: "Clampett Oil and Gas Corp.",
    phone: "8754554531",
    billing: "Palo Alto",
    state: "CA",
    country: "USA",
    image: C_logo,
    company_code: "",
    customer_code: "",
    business_code: "",
    company_number: "",
    group_: "",
    relationship: "",
    registration_date: null,
    head_quater_responsible: "",
    Business_strategy_area: "",
    Corporate_number: "",
    group_classification: "",
    Transaction_classification: "",
    company_name: "Clampett Oil and Gas Corp.",
    company_name1: "",
    english_company_name: "",
    Business_number: "",
    start_date: null,
    end_date: null,
    representative: "",
    repr_resident_number: "",
 	  state_business: "",
    type_: "",
    postal_code: "",
    business_address: "",
    industry_class: "",
    discount_policy: "",
    trade_start_date: null,
    trade_end_date: null,
    estimate_request_: "",
    repr_birthday: null,
    repr_lunar_birthday: "",
    repr_solar_birthday: null,
    company_postal_code1: "",
    company_address1: "",
    company_postal_code2: "",
    company_address2: "",
    company_telephone1: "8754554531",
    company_fax1: "",
    company_telephone2: "",
    compa: "",
  },
  {
    id: 2,
    company: "Soylent Corp",
    phone: "8754554531",
    billing: "Havier Street",
    state: "CA",
    country: "India",
    image: C_logo2,
    company_code: "",
    customer_code: "",
    business_code: "",
    company_number: "",
    group_: "",
    relationship: "",
    registration_date: null,
    head_quater_responsible: "",
    Business_strategy_area: "",
    Corporate_number: "",
    group_classification: "",
    Transaction_classification: "",
    company_name: "Soylent Corp",
    company_name1: "",
    english_company_name: "",
    Business_number: "",
    start_date: null,
    end_date: null,
    representative: "",
    repr_resident_number: "",
 	  state_business: "",
    type_: "",
    postal_code: "",
    business_address: "",
    industry_class: "",
    discount_policy: "",
    trade_start_date: null,
    trade_end_date: null,
    estimate_request_: "",
    repr_birthday: null,
    repr_lunar_birthday: "",
    repr_solar_birthday: null,
    company_postal_code1: "",
    company_address1: "",
    company_postal_code2: "",
    company_address2: "",
    company_telephone1: "8754554531",
    company_fax1: "",
    company_telephone2: "",
    compa: "",
  },
  {
    id: 3,
    company: "Umbrella",
    phone: "8754554531",
    billing: "Havier Street",
    state: "CA",
    country: "India",
    image: C_logo3,
    company_code: "",
    customer_code: "",
    business_code: "",
    company_number: "",
    group_: "",
    relationship: "",
    registration_date: null,
    head_quater_responsible: "",
    Business_strategy_area: "",
    Corporate_number: "",
    group_classification: "",
    Transaction_classification: "",
    company_name: "Umbrella",
    company_name1: "",
    english_company_name: "",
    Business_number: "",
    start_date: null,
    end_date: null,
    representative: "",
    repr_resident_number: "",
 	  state_business: "",
    type_: "",
    postal_code: "",
    business_address: "",
    industry_class: "",
    discount_policy: "",
    trade_start_date: null,
    trade_end_date: null,
    estimate_request_: "",
    repr_birthday: null,
    repr_lunar_birthday: "",
    repr_solar_birthday: null,
    company_postal_code1: "",
    company_address1: "",
    company_postal_code2: "",
    company_address2: "",
    company_telephone1: "8754554531",
    company_fax1: "",
    company_telephone2: "",
    compa: "",
  },
  {
    id: 4,
    company: "Umbrella",
    phone: "8754554531",
    billing: "Havier Street",
    state: "CA",
    country: "India",
    image: C_logo2,
    company_code: "",
    customer_code: "",
    business_code: "",
    company_number: "",
    group_: "",
    relationship: "",
    registration_date: null,
    head_quater_responsible: "",
    Business_strategy_area: "",
    Corporate_number: "",
    group_classification: "",
    Transaction_classification: "",
    company_name: "Umbrella",
    company_name1: "",
    english_company_name: "",
    Business_number: "",
    start_date: null,
    end_date: null,
    representative: "",
    repr_resident_number: "",
 	  state_business: "",
    type_: "",
    postal_code: "",
    business_address: "",
    industry_class: "",
    discount_policy: "",
    trade_start_date: null,
    trade_end_date: null,
    estimate_request_: "",
    repr_birthday: null,
    repr_lunar_birthday: "",
    repr_solar_birthday: null,
    company_postal_code1: "",
    company_address1: "8754554531",
    company_postal_code2: "",
    company_address2: "",
    company_telephone1: "",
    company_fax1: "",
    company_telephone2: "",
    compa: "",
  },
];

export const data_user = [
  {
    userId: "demo", 
    userName: "demo", 
    name: "demo", 
    email: "demo@demo.com", 
    isAdmin: false, 
    password: "", 
    phone: "02-123-1234",
    organization: "", 
    subscribeToOwnCards: false, 
    createdAt: "2024-02-01", 
    updatedAt: "2024-02-01", 
    deletedAt: "", 
    language: "ko",
    passwordChangeAt: "", 
    avatar: "", 
    detail: "test demo user"
  },
 
];