import React from 'react';
import { atom } from 'recoil';

export const defaultCompany = {
    company: "",
    phone: "",
    billing: "",
    state: "",
    country: "",
    image : null,
    company_code: "",
    customer_code: "",
    business_code: "",
    company_number: "",
    group_: "",
    relationship: "",
    registration_date: null,
    head_quater_responsible: "",
    Business_strategy_area: "",
    Corporate_number: "",
    group_classification: "",
    Transaction_classification: "",
    company_name: "",
    company_name1: "",
    english_company_name: "",
    Business_number: "",
    start_date: null,
    end_date: null,
    representative: "",
    repr_resident_number: "",
 	state_business: "",
    type_: "",
    postal_code: "",
    business_address: "",
    industry_class: "",
    discount_policy: "",
    trade_start_date: null,
    trade_end_date: null,
    estimate_request_: "",
    repr_birthday: null,
    repr_lunar_birthday: "",
    repr_solar_birthday: null,
    company_postal_code1: "",
    company_address1: "",
    company_postal_code2: "",
    company_address2: "",
    company_telephone1: "",
    company_fax1: "",
    company_telephone2: "",
    compa: "",
};

export const atomCurrentCompany = atom({
    key: "currentCompany",
    default: defaultCompany,
});

export const atomAllCompanies = atom({
    key: "allCompany",
    default: [],
});